version: '3.8'
services:
  web:
    build:
      context: .
      args:
        NEWS_API_KEY: ${NEWS_API_KEY}
        NEXT_SERVERLESS_API_URL: ${NEXT_SERVERLESS_API_URL}
        GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
    ports:
      - '3000:3000'
    env_file:
      - .env
