version: '3.8'
services:
  web:
    build:
      context: .
      args:
        NEWS_API_KEY: ${NEWS_API_KEY}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NEWS_API_KEY: ${NEWS_API_KEY}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
